var SchattenSkulpturEvents = [
[ '21.03.2017 22:33:46',
  'Kubeja, Jochen',
  'WOGA Garten',
  '',
  'WOGA-Skulpturen-Garten: Der urige, versteckt liegende Garten beherbergt mehrere Skulpturen und strahlt eine gelassene und peacige Atmosphäre aus. Ein wirklich schöner Ort, bewacht von den Wächtern des Gartens. Vom 18. bis 20. August findet hier die WOGA statt, die WohnzimmerGArtenschau des Wohnzimmer e. V. Weitere KünstlerInnen sind eingeladen, hier auszustellen.',
  'Bei gutem Wetter: Anrufen unter 0177 931 7943 oder Mail: jochen.kubeja@gmail.com',
  'Zum Guten Hirten, 200 m hinter der Kanalbrücke stadtauswärts links rein am Schild "WOGA"',
  'Austellung',
  'Skulpturen',
  '51.962821',
  '7.668446',
  '',
  '',
  'always' ]
,
[ '03.04.2017 20:18:48',
  'Kubeja, Jochen',
  'Graffiti Kunst',
  '',
  'Die Fabrikwand ist offiziell erlaubte Graffiti-Fläche. Kunst-Studierende sprühen hier gerne ihre Werke an die Wand. So entsteht eine ständig wechselnde Graffiti-Ausstellung auf hohem Niveau. Häufig sind die Künstler/innen bei der Arbeit anzutreffen.',
  'immer',
  'Euler Str. 21, Münster',
  '',
  '',
  '51.941264',
  '7.639899',
  'IMG_0217.JPG',
  '',
  'always' ]
,
[ '03.04.2017 20:43:06',
  'Kubeja, Jochen',
  'Elefant',
  'www.wohnzimmer-ev.de',
  'Ein aus weißem Marmor gehauener Elefant, etwa 1,10 groß',
  'immer',
  'Nieberdingstr. 11, 48155 Münster',
  '',
  '',
  '51.943400',
  '7.645780',
  '',
  '',
  'always' ]
,
[ '10.04.2017 12:29:32',
  'Jaffke, Michael',
  'Die Große',
  'www.farbig-und-rostig.de',
  'Skulpur aus Schrott und Holz',
  'August 2017',
  'noch unbekannt',
  '',
  '',
  '',
  '',
  '',
  '',
  'always' ]
,
[ '02.05.2017 19:39:16',
  'Kubeja, Jochen',
  'Critical Mass Münster',
  'https://www.facebook.com/criticalmass.ms/',
  'Werde Teil der Masse und zeig, dass Radfahrer im Verband im Straßenverkehr ein  s werden und zu einem riesigen Fahrzeug verschmelzen. \n\n> 16 Radfahrer = Verband = auf der Straße fahren \n\nKeine Demo, Veranstaltung oder Rennen, sondern Performance, Flashmob und Haltung. Und auch einfach und entspannt mit anderen durch die Stadt radeln.\n\nSpät dran oder Start verpasst? Kein Problem!\nMit den Apps Critical Maps und Glympse könnt ihr uns auch als Nachzügler noch finden und zur Masse dazustoßen.\nCritical Maps: Einfach App runterladen und öffnen. Der aktuelle Standort der CM wird angezeigt.\nGlympse: App runterladen und nach dem Tag "criticalmassMS" suchen, auch hier wird dann der Standort angezeigt.\nFür alle die pünktlich da sind: Ladet euch doch auch die App runter, startet Sie beim losfahren und teilt damit euren Standort. Das ermöglicht den anderen uns zu finden. Je mehr Leute mitmachen, desto genauer wirds!\n\nBis gleich!\n',
  'Fr., 26.05.2017\nFr., 30.06.2017\nFr. 28.07.2017\nFr. 25.08.2017\nFr., 29.09.2017\nStart ist jeweils um 19.00 Uhr.',
  'Treffpunkt Domplatz Münster',
  'Kunst-Flashmob',
  '',
  '51.962077',
  '7.625366',
  'CriticalMassMuenster.jpg',
  [ '2017-05-26',
    '2017-06-30',
    '2017-07-28',
    '2017-08-25',
    '2017-09-29' ],
  'repeating' ]
,
[ '03.05.2017 12:06:30',
  'Weyand, Georgios',
  'Der Sonnenwagen',
  'http://www.facebook.com/DerSonnenwagen/',
  'Kinetische Gemeinschafts-Skulptur mit medialer Installation',
  '24h ohne mediale Installation an der Dammstr. 19 - an ausgewählten Tagen und Orten mit medialer Installation',
  'Dammstr. 19 / verschiedene Orte in Münster',
  'Sonstiges',
  '',
  '51.951001',
  '7.632366',
  'sonnenwagen3.jpg',
  '',
  'always' ]
,
[ '04.05.2017 19:49:13',
  'Künnemann, Ursula',
  'Skulpturen-Garten Ahlener Gruppe',
  '',
  'Gegenüber des Zwingers an der Promenade führt ein schmaler Weg (markiert) direkt in den einladenden Skulpturen-Garten. Die Ahlener KünstlerInnengruppe arbeitet seit über 10 Jahren an Skulpturen aus Sandstein und Speckstein. Eine Auswahl der Werke von 12 unterschiedlichen Künstlern präsentieren sie in dem hausumläufigen Garten. Die Gruppe verbindet der Werkstoff, die Motivwahl erfolgt individuell durch die jeweilige KünstlerIn. Die Künstler sind anwesend und arbeiten zum Teil vor Ort.',
  'So., 27.08.2017, 13.00 bis 18.00 Uhr',
  'Zeppelinstr. 6, 48147 Münster',
  'Ausstellung',
  '',
  '51.968199',
  '7.631402',
  '',
  [ '2017-08-27' ],
  'once' ]
,
[ '02.06.2017 14:15:52',
  'Schulze, Einar',
  'Vernissage "lyme" von Einar Schulze bei KnowMe',
  'irgendeinar.blogspot.de',
  'Ölgemälde von Einar Schulze, ausgestellt bei KnowMe.',
  '24. Juni ab 19:00 Uhr',
  'Diepenbrockstraße 11, Hinterhof, 48145 Münster',
  'Ausstellung',
  'Gemälde',
  '51.958503',
  '7.640315',
  '',
  [ '2017-06-24' ],
  'once' ]
,
[ '02.06.2017 14:15:52',
  'Schulze, Einar',
  '"lyme" von Einar Schulze bei KnowMe',
  'irgendeinar.blogspot.de',
  'Ölgemälde von Einar Schulze, ausgestellt bei KnowMe.',
  '24. Juni - 24. Juli 2017 / Mittwochs 9 – 16 Uhr und Freitags 9 – 14 Uhr',
  'Diepenbrockstraße 11, Hinterhof, 48145 Münster',
  'Ausstellung',
  'Gemälde',
  '51.958503',
  '7.640315',
  '',
  [ '2017-06-28',
    '2017-06-30',
    '2017-07-05',
    '2017-07-07',
    '2017-07-12',
    '2017-07-14',
    '2017-07-19',
    '2017-07-21' ],
  'repeating' ]
,
[ '09.05.2017 19:34:15',
  'Kordt, Monika Veronika',
  'Kunstgewirk',
  '',
  'Unterschiedliche gestaltete Stühle',
  'Steht noch nicht fest',
  'Steht noch nicht fest',
  'Event',
  '',
  '',
  '',
  '',
  '',
  'always' ]
,
[ '12.05.2017 15:55:24',
  'Luckmann, Helmut',
  'Aus-Stellung, Aus-Schnitte',
  '',
  'Im Rahmen eines "Offenen Aleliers" ist u.a. das Bild zu sehen, das im letzten Jahr bei einer Performance im Schlossgarten entstand. \nDie Tänzer Alice Cerrato und Antonio Rusciano begleiten eine Transformation dieses großen Bildes, bei der die Besucher einen bestimmten Aussnitt wählen können, der von mir vor Ort zu einem neuen Objekt gestaltet wird.\nWir geben auch gerne Autogramme ins Booklet, das die gesamte Performance inkl. DVD dokumentiert.\nDie einzelnen Aktionen werden jeweils um 12, 14, und 16 Uhr starten. \nSie sind herzlich eingeladen, sich an diesem Tag inspirieren und überraschen zu lassen. ',
  'So., 11.06.2017, 11 bis 17 Uhr',
  'Atelier Werse 27, Pleistermühlenweg, Biohof Borghoff',
  'Ausstellung',
  'Gemälde',
  '',
  '',
  '',
  '',
  'always' ]
,
[ '15.05.2017 14:11:37',
  'Teresa Häuser',
  'womens march Münster',
  'Werkstatt-Kinderhaus.de',
  '\n    "Women’s march – Münster" eine Skulpturenarbeit der "Werkstatt für Gestaltung"\n\nWir formen eine Skulpturengruppe aus Figuren, die in der "Werkstatt für Gestaltung" von vielen kunstschaffenden Menschen entstanden sind. Dazu gießen wir unsere vorhandenen Tonskulpturen, die wir 2016 zusammen bei der Ausstellung "Kunst am Rand" als "Frauen in Münster" gezeigt haben, mit Gips ab und replizieren daraus viele neue Büsten aus Pappmaschee. Diese entstandenen Doubles unserer Sklupturen grundieren wir mit pinker Farbe, kleistern nochmal eine Schicht Zeitungspapier darauf und stellen sie gesammelt in verschiedenen Formationen zum "women´s march" auf. Die Figuren beenden ihren Marsch schlussendlich an der Wiese gegenüber dem Aasee/Promenade. Wir holen damit die mittlerweile internationale Bewegung "womens march" (urspünglich aus den USA) nach Münster und eroberen uns den öffentlichen Raum der Stadt zurück, der im Rahmen den "Skulptur-Projekte 2017" nur von international renommierten, aber nicht aus Münster stammenden Künstlern belegt ist. Der Platz an der Promenade ist bewusst als "Dialog" zu dem Motto „Münster bekennt Farbe“ gewählt – und versucht eine Erweiterung und Übertragung des hübschen, blumigen Spruchs: In Anlehnung an die pinken „women’s hats“ der Bewegung sind unsere Figuren pink und repräsentieren die verschiedenen, vielfältigen Menschen unserer Stadt, sichtbar durch unterschiedliche Altersstufen, Kulturgruppen, Ethnien, Religionszugehörigkeiten, Geschlechter. Die Zeitungen, die in der äußeren Ummantelung der Figuren verwendet werden, sind international und stellen eine Anspielung auf die Sprachenvielfalt und Pressefreiheit, mithin eine Reminiszenz an die Allgemeinen Menschenrechte dar.\n',
  'im Zeitraum 11.-17.9.2017',
  'Am Liebsten auf der Wiese Promenade/Aasee "Münster bekennt Farbe" als Abschluss. Eventuell auch andere Plätze an der Promenade die , die Bewegung dorthin markieren. Uns ist noch nicht klar, ob wir die Veranstaltung als Mahnwache/Demonstration oder Kunstausstellung anmelden. Wir arbeiten an dieser Frage und würden das Projekt bis zur  Beantwortung derselben noch nicht veröffentlichen wollen. ',
  'Ausstellung',
  'Skulptur',
  '51.957270',
  '7.620800',
  '',
  [ '2017-09-11' ],
  'once' ]
,
[ '18.05.2017 18:42:49',
  'Cardaun, Gilla',
  'Fahrt ins Blaue',
  'www.ambulantegalerie.de',
  'Ein umgestaltetes Verkehrs-Schild, bemalt mit Acrylfarbe',
  'Mo - Fr: 10 bis 18 Uhr\nSa: 10 - 14 Uhr',
  'In der Fahrrad-Werkstatt Lila Leeze, Dortmunder Str. 11, 48155 Münster',
  'Ausstellung',
  'Gemälde',
  '51.955298',
  '7.641913',
  '',
  '',
  'always' ]
,
[ '18.05.2017 20:09:09',
  'SchattenSkulptura',
  'Offizieller Auftakt SchattenSkulptura',
  'www.wohnzimmer-ev.de',
  'Zum Auftakt unserer SchattenSkulptura starten wir mit einem Kunst-Picknick an der Promenade. Bringt Picknick-Decken mit und alles, was dazu gehört. Also lecker Essen und Trinken, Kerzenfackeln, Instrumente, Mucke... \nUnd: Natürlich ein Stück Kunst. Oder auch zwei.\nKommt vorbei und startet mit uns in den ultimativen Kunst-Sommer! \n(JedeR nimmt mit nach Haus, was er/sie mitbringt)',
  'Freitag, 16.06.2017 ab 20 Uhr',
  'Promenade, auf der Wiese direkt westlich vom Zwinger ',
  'Flashmob',
  'Skulptur',
  '51.967742',
  '7.630874',
  '',
  [ '2017-06-16' ],
  'once' ]
,
[ '23.05.2017 19:40:51',
  'Kayalie, Fouad',
  'Syrian Sculptures - Gips and Beton',
  '',
  'Es werden Fotos hinterlegt, die die Kunst beschreiben...',
  'Nach Terminvereinbarung - suche Außerdem Ausstellungsräume oder Gemeinschaftsausstellungen',
  'Die Skulpturen stehen bei mir im Wohnzimmer. Kontaktiere mich und wir können einen Termin vereinbaren: fouadkayalie@gmail.com',
  'Ausstellung',
  'Skulptur',
  '51.983640',
  '7.641120',
  'event101.jpg',
  '',
  'always' ]
,
[ '25.05.2017 20:14:53',
  'Kötter, Lisa',
  'Skulptur-to-go- Automat',
  'strohzugoldlisa.blogspot.de',
  'Ich werde einen fahrbaren Skulpturen-"Automaten" bauen. Dort kann jeder gegen eine kleine spende eine kleine Skulptur für die Hosentasche( und dann zu Hause fürs Sideboard) erstehen. \nDie Kunstfreunde werden mit dem "Automaten" auch reden können, er kann Fragen  zu den kleinen Kunstwerken beantworten.\nDie kleinen Skulpturen werden von mir persönlich ( vor allem aus upgecycleten  Altmaterial) gefertigt und in entsprechend gestaltete Streichholzschachteln verpackt, die jeweils Teil des kleinen Werkes sein werden.\n\nIch bin freischaffende Künstlerin aus Münster. Nah Göttingen habe ich ein zweites Atelier. Seit über 20 Jahren mache ich meine Kunst vor allem aus Altmaterialien. So ist der Name meines Blogs "strohzugold" Programm.\nVielen Dank für diese tolle Idee der Schattenskulptur! Und für die Möglichkeit zur Vernetzung. ',
  '(16.,)17.,18. Juni, 24.,25. Juni, 1.,2. Juli, 22,.23. Juli jeweils ca.14-16 Uhr',
  'Um die Kreuzschanze herum (Promenade)',
  'Fahrbarer "Automat"',
  'Skulpturen- "Automat"',
  '',
  '',
  '',
  '',
  'always' ]
,
[ '06.06.2017 23:06:05',
  'Eckardt, Linda',
  'Phantastische Malerei',
  '',
  'Acryl auf Leinwand',
  '',
  'Drinnen in einem Zimmer, Raum, Halle',
  'Ausstellung',
  'Gemälde',
  '51.934346',
  '7.594275',
  '',
  '',
  'always' ]
,
[ '12.06.2017 14:58:15',
  'Jaffke, Michael',
  'Offenes Atelier "farbig und rostig"',
  'www.farbig-und-rostig.de',
  'Wir öffnen unser Atelier und zeigen unsere neuesten Objekte, aber auch ältere Werke der letzten Jahre. Es handelt sich dabei um Acrylbilder, sowie Skulpturen aus Schrott und Fundstücken. \nDie Location liegt am Ufer der Werse und ist am Besten mit dem Fahrrad oder zu Fuß erreichbar. Autofahrer könnten evtl. Parkprobleme bekommen und sollten in der Umgebung der Kapelle am Beginn der Zielstraße parken.\nNähere Infos unter www.farbig-und-rostig.de',
  '09.09., 10.09., 23.09., 24.09. jeweils von 11 bis 18 Uhr',
  '48157 Münster, Reetbusch 71',
  'Ausstellung',
  'Skulpturen und Acrylbilder',
  '51.971413',
  '7.696116',
  '',
  [ '2017-09-09', '2017-09-10', '2017-09-23', '2017-09-24' ],
  'repeating' ]
,
[ '12.06.2017 17:37:14',
  'Kubeja. Jochen',
  'Graffiti-Wand - Urban Street Art',
  'www.wohnzimmer-ev.de',
  'Zwischen Nieberdingstraße und Kanalufer führt ein Weg zur Marine Jugend e. V. entlang der Gebäuderückseite von Getränke Lappe. Diese Wand wird von zahlreichen, tollen Graffiti-Werken verziert. Wahre Urban Street Art von bekannten und geschätzten Künstlern wie Rookie the Weird (www.facebook.com/liquidluck.de) und vielen Anderen',
  'Rund um die Uhr',
  'Nieberdingstraße 12, 48155 Münster (Gebäuderückseite)',
  'Urban Street Art',
  'Graffiti',
  '51.944291',
  '7.644210',
  'IMG_0201.JPG',
  '',
  'always' ]
,
[ '12.06.2017 18:07:23',
  'Kubeja, Jochen',
  'Graffiti-Wand Rebholz - Urban Street Art',
  'www.wohnzimmer-ev.de',
  'Die Gebäudewand der Eisen- und Metallgießerei Rebholz ist eine der lebhaftesten und beliebtesten Graffiti-Wände der Stadt. Die Ausstellung ist ständig im Wandel. Qualitativ hochwertige Werke sind hier zu bestaunen. Seit 2007 ist die Wand durch die Ordnungspartnerschaft Graffiti für Sprayer freigegeben. Ein Besuch lohnt sich immer. Insbesondere am Wochenende sind die Künstler bei der Arbeit anzutreffen. ',
  'Rund um die Uhr',
  'Euler Straße 21, 48155 Münster',
  'Ausstellung',
  'Graffiti - Urban Street Art',
  '51.941264',
  '7.639899',
  '',
  '',
  'always' ]
,
[ '12.06.2017 19:27:23',
  'Kubeja, Jochen',
  'Schiff',
  'https://www.facebook.com/Das-Nieber-Ding-eV-1406239566266186/',
  'Der Künstler Daniel Dubbrow ist versiert im Umgang mit Holz. Aus Holzresten und Holzabfällen kreiert er fantastische Skulpturen, die in der Regel begehbar und erlebbar sind. So auch sein Schiff von 2016, das am NieberDing vor Anker liegt. Über einen Holzsteg, gesäumt von dicken Tauen, kann das Schiff betreten werden. Aber Vorsicht, der Seegang ist nicht ganz ohne und schüttelt das Schiff samt Passagiere mächtig durch. ',
  'Rund um die Uhr',
  'Nieberdingstr. 26, 48155 Münster. Wiese nördlich vor dem Haus',
  'Ausstellung',
  'Skulptur',
  '51.942200',
  '7.643010',
  'IMG_0208.JPG',
  '',
  'always' ]
,
[ '12.06.2017 18:42:53',
  'Kubeja, Jochen',
  'Schiffer-Schaukel',
  'https://www.facebook.com/Das-Nieber-Ding-eV-1406239566266186/',
  'Ein weiteres Upcycling-Werk des Künstlers Daniel Dubbrow und Freunden, die Schiffer-Schaukel, das ebenfalls "begehbar" und erlebbar ist. Steig ein, schließ die Augen und lass die Seele baumeln...',
  'Rund um die Uhr',
  'Nieberdingstraße 26, 48155 Münster. Wiese nördlich vor\'m Haus',
  'Ausstellung',
  'Skulptur',
  '',
  '',
  '',
  '',
  'always' ]
,
[ '12.06.2017 19:11:22',
  'Kubeja, Jochen',
  'Graffiti-Gemälde Under the Bridge',
  'www.wohnzimmer-ev.de',
  'Unter der Umgehungsstraßen-Brücke ist das wohl größte Graffiti-Gemälde der Stadt zu sehen. Die komplette östliche Wand ziert ein Werk, thematisch passend zur Wasserkante. ',
  'Rund um die Uhr',
  'Unter der Umgehungsstraßenbrücke, Eulerstraße 15',
  'Ausstellung',
  'Gemälde',
  '51.939389',
  '7.638609',
  'IMG_0218.JPG',
  '',
  'always' ]
,
[ '12.06.2017 19:24:13',
  'Kubeja, Jochen',
  'Graffiti-Werke - Urban Street Art',
  'www.wohnzimmer-ev.de',
  'Am Hawerkamp finden sich überall außergewöhnliche Graffitis, geschweisste Skulpturen und vielfältige Urban Street Art.\n"Ein besonderes Gebiet in Münster zum Ausgehen ist der Hawerkamp [... Hier] hat sich eine außergewöhnliche künstlerische und musikalische Szene etabliert, die jährlich über 120.000 Besucher anzieht. Neben den zahlreichen Musikevents in den einzelnen Clubs ist diese Besucherzahl auch auf das jährlich stattfindende Hawerkamp-Festival und den offenen Ateliers der über 50 Künstler zurückzuführen. Bei der Bewerbung Münsters zur Kulturhauptstadt Europas 2010 war der Hawerkamp einer der kulturellen Schwerpunkte neben Prinzipalmarkt und Picasso-Museum. In einem bundesweit einzigartigen Projekt wird seit dem 1. Januar 2006 das alternativ geprägte Gelände durch den Verein "Erhaltet den Hawerkamp" eigenverantwortlich verwaltet."\nQuelle: http://wiki.muenster.org/index.php/Hawerkamp',
  'Rund um die Uhr',
  'Am Hawerkamp 31, Münster',
  'Ausstellung',
  'Urban Street Art',
  '51.943878',
  '7.638363',
  '',
  '',
  'always' ]
,
[ '17.06.2017 01:40:10',
  'Jasper, Lennart',
  'Metzer58 - MITMACH - Videodreh',
  'www.metzer58.de',
  '17:00 Uhr\nMITMACH-Videodreh von METZER 58 an der Kiosk Ecke(Hansaring)\nDas Konzept: Gute Laune und Kamera draufhalten...ja, genial, oder?!?\n\n18:30 Uhr\nAufbruch zum Konzert + Kino im Triptychon\n\nKONZERT im Triptychon mit:\nFRESSE, C4SERVICE, METZER 58, NO BRAINZ, PANDEMIE\n+ KINO von:\nNO BRAINZ Filmproductions-Filmpremiere, KINO OHNE TALENT, THUNDERFUCK\n+ POPCORN :)\n( Konzerteintritt 5€ )',
  '',
  'Kiosk Ecke, Hansaring 2',
  'Performance',
  'Gute Laune',
  '51.952749',
  '7.636804',
  '',
  [ '2017-06-23' ],
  'once' ]
,
[ '19.06.2017 08:35:39',
  'Dr. Köpfer Karlheinz',
  'Ausstellung',
  'www.karlheinz-koepfer.de',
  'Karlheinz Köpfer: „Holzfantasien“ Skulpturen aus Holz in den Schaufenstern Des Modehauses Petzhold, Prinzipalmarkt 5',
  'Mo - Sa 9:30 - 19 Uhr; Schaufenster rund um die Uhr zu besichtigen',
  'Modehaus Petzhold, Prinzipalmarkt 5',
  'Ausstellung',
  'Skulptur',
  '51.962180',
  '7.628270',
  '',
  '',
  'always' ]
,
[ '19.06.2017 13:56:16',
  'Beckmann, Julian',
  'Spass im Alltag',
  '-',
  'Kleine Kunsthefte zum mitnehmen (Stil: grotesk/Karikatur/Fanzine)',
  'wie es am besten passt :)',
  'Ich suche nach einem geeigneten Ort, an dem ich meine kleinen Hefte auslegen kann. ( ca.14 x 20 cm)',
  'Pappaufsteller, Kiste o.ä.',
  'Magazine / Kunsthefte',
  '',
  '',
  '',
  '',
  'always' ]
,
[ '20.06.2017 16:33:30',
  'Luttermann, Christian',
  '-',
  '-',
  '-',
  '',
  'Garten Sonnenbergweg, Berg Fidel',
  '',
  '',
  '',
  '',
  '',
  '',
  'always' ]
,
[ '21.06.2017 13:50:32',
  'Magusa, Guillermo',
  'Bier und Papier',
  '',
  'Zusammen kommen, Bier bestellen, anfangen zu zeichnen/malen, nice Unterhaltungen und entspannen.',
  'Jeden Montag ab 18 Uhr (26.6, 3.7, 10.7, 17.7, 24.7, 31.7, 7.8, 14.8, 21.8, 28.8, 4.9, 11.9, 18.9, 25.9)',
  'Plan B, Hansaring 9',
  'Workshop',
  '',
  '51.953100',
  '7.637971',
  '',
  [ '2017-06-26',
    '2017-07-03',
    '2017-07-10',
    '2017-07-17',
    '2017-07-24',
    '2017-07-31',
    '2017-08-07',
    '2017-08-14',
    '2017-08-21',
    '2017-08-28',
    '2017-09-04',
    '2017-09-11',
    '2017-09-18',
    '2017-09-25',
    '2017-10-02' ],
  'repeating' ]
,
[ '21.06.2017 14:26:22',
  'Jochen Kubeja',
  'Guerilla-Urban-Gardening',
  'www.wohnzimmer-ev.de',
  'Der kunstvoll angelegter Guerilla-Garten inmitten urbaner Verkehrswüsten bildet eine Oase des Grüns in der Stadt. Zwischen der vierspurigen Steinfurter Straße und dem Rad- und Fußweg gärtnert eine ältere Lady und schafft ein kleines, ansehnliches Biotop. Mit Liebe und grünem Daumen pflanzt Carmen Vellani alles, was blüht. Die 86 jährige stammt ursprünglich aus Brasilien. In diesem trockenem Sommer muss sie besonders viel gießen und kommt kaum gegen die Dürre an. Wo soll das Grundwasser in einer Betonwüste auch herkommen?',
  'Rund um die Uhr',
  'Steinfurter Str. 46',
  'Ausstellung',
  'Guerilla-Gardeing',
  '51.971290',
  '7.609600',
  '',
  '',
  'always' ]
,
[ '21.06.2017 15:16:25',
  'Kubeja, Jochen',
  'Guerilla-Skulptur: "Brave America"',
  'www.wohnzimmer-ev.de',
  'Der münsteraner Künstler Christian Nachtigäller hat mit seiner Guerilla-Skulptur "Brave America" mal wieder für Aufsehen gesorgt. In einer Nacht und Nebel-Aktion stellte er seine 3 m hohe Skulptur auf. Sie stellt eine amerikanischen Flagge dar, gespickt mit kleinen Autos, rot angemalten Zinnsoldaten, Fernbedienungen, Kreditkarten, eine blau gestrichenen Öltonne und auf dem Rasen liegenden Sternen. Für den Standort wählte er die korrespondierende Nähe zum Skulptur Projekt 2017 "Momentary Monument - The Stone" und stellt mit seiner USA-Kritik einen Bezug zum Train-Denkmal her, dass an die Kolonialkriege erinnert.\nDas Kunstwerk wurde nur 48 Stunden nach seiner Aufstellung vom Ordnungsamt entfernt - aus Verkehrssicherungsgründen, wie das Presseamt der Stadt Münster verlautbaren ließ.\n"Es ist das Schicksal der Anarchisten und Unruhe-Stifter, dass sie mit den Ordnungskräften in Konflikt geraten." (Quelle: WN)\nSo so. \nJetzt hat der Künstler am Rande der Stern-Apotheke ein privates Grundstück gefunden, um sein Werk unbehelligt auszustellen. Geht doch!',
  'Rund um die Uhr',
  'Ludgeristraße 66 / Ecke Promenade',
  'Ausstellung',
  'Skulptur',
  '51.95663',
  '7.62617',
  '',
  '',
  'always' ]
,
[ '22.06.2017 09:23:24',
  'Dr. köpfer, Karlheinz',
  'Künstlerische Dimensionen Bilder und Skulpturen von Ines Klich und Karlheinz Köpfer',
  'www.karlheinz-koepfer.de',
  'Vernissage am Sonntag 2. Juli um 15:30 Uhr',
  'zu den gewöhnlichen Bürozeiten; ausserhalb dieser Zeiten nach tel. Vereinbarung möglich (0251-135330)',
  'EFL Beratungsstelle Münster, Antoniuskirchplatz 21, 48151 Münster',
  'Ausstellung',
  'Skulptur',
  '51.954530',
  '7.622170',
  '',
  [ '2017-07-02' ],
  'once' ]
,
[ '23.06.2017 10:30:35',
  'Newels, Martin',
  'Vernissage@B/7 I Kunst beim Optiker',
  'http://www.new-optics.de/muenster-galerie-optiker-new-optics-b7gallery.html',
  'New Optics by Martin Newels möchte mit den Kunstprojekt B/7 Gallery Künstlern eine Plattform und einen Raum zur Verfügung stellen, indem ihre Projekte im Rahmen einer Kunstausstellung oder eines Konzertes in einer außergewöhnlichen Umgebung präsentiert werden. Besonders angesprochen werden gerade die Künstler, die sich bisher nicht in die Öffentlichkeit mit ihrer Begabung gewagt oder noch keinen Platz gefunden haben ihre Kunst zu präsentieren.',
  'Mo-Fr. 9.30 - 18.30 Sa 10.00 - 16.00 Vernissage@B/7 15.07/ 19.08/ 02/09 16.00 - 18.00',
  'B/7 Gallery by Martin Newels in den Räumen von New Optics Münster by Martin Newels I Bült 7 I 48143 Münster',
  'Ausstellung',
  'Gemälde',
  '51.964154',
  '7.630927',
  '',
  [ '2017-07-15', '2017-08-19', '2017-09-02' ],
  'repeating' ]
,
[ '28.06.2017 10:46:14',
  'max.hurle@web.de',
  'Emil et Psyche',
  'max-hurlebaus.de',
  'Nicht Hörspiel, nicht Lyrik, nicht Gedicht, nicht Musik. \nExklusive Vorstellung einer akustischen Reise zwischen Traum und Wirklichkeit. ',
  'Findet am 8.7.2017 statt. Vorstellungsbeginn: 14, 15 und 16 Uhr. ',
  'Bohlweg 37',
  'Event',
  'Klangreise',
  '51.967455',
  '7.642436',
  '',
  [ '2017-07-08' ],
  'once' ]
,
[ '03.07.2017 13:37:58',
  'Wilken, Thomas',
  '1. Fotoaustellung Thomas Wilken',
  'www.thomaswilken.com',
  'Ich würde meine Fotografien wie folgt beschreiben: \nAktfotografien auf denen die dargestellten Frauen nicht als sexuelle Objekte dargestellt werden. Vielmehr soll die "Nacktheit", in der meist natürlichen Umgebung, Zerbrechlichkeit darstellen und Pur sein. Dadurch dass auf den meisten Bildern keine Gesichter zu erkennen sind, geht es nicht speziell um den/die Menschen auf dem Foto (wie z.B. in einem Portrait) sondern um die Verschmelzung zwischen Mensch und Natur. Vernissage: 26.07.2017 ab 18 Uhr !\n',
  'Mittwochs 9 – 16 Uhr und freitags 9 – 14 Uhr\nTermine nach Absprache möglich.',
  'KnowMe, Diepenbrockstrasse 11a, Hinterhof, 48145 Münster',
  'Ausstellung',
  'Fotografie',
  '51.958503',
  '7.640315',
  '',
  [ '2017-07-26',
    '2017-07-28',
    '2017-08-02',
    '2017-08-04',
    '2017-08-09',
    '2017-08-11',
    '2017-08-16',
    '2017-08-18',
    '2017-08-23',
    '2017-08-25',
    '2017-08-30',
    '2017-09-01',
    '2017-09-06',
    '2017-09-08',
    '2017-09-13',
    '2017-09-15' ],
  'repeating' ]
,
[ '03.07.2017 17:49:51',
  'Simsek Meryem',
  'Mandalas Weben mit Miss Miri',
  'www.impulseearth.com',
  'Workshop',
  '15:00-18:00',
  'Leonardo Campus Grüne Beete Fest',
  'Workshop',
  '',
  '51.974959',
  '7.600039',
  '',
  '',
  'always' ]
,
[ '15.07.2017 20:55:33',
  'Schiwy, Monika',
  'Tischgespräche und Ausstellung',
  'www.monikaS.de',
  'Tischgespräche rund um einen alten Tisch im Atelier ART & Weise',
  '13.08.2017   11:30 Uhr bis 17:00 Uhr',
  'Atelier ART & Weise, Monika Schiwy, Haus Coerde, Coermühle 50, 48157 Münster',
  'Event',
  'ART Salon ',
  '52.007830',
  '7.625540',
  '',
  [ '2017-08-13' ],
  'once' ]
,
[ '20.07.2017 10:48:07',
  'Linnenbrink, Dorothea',
  'Glücksklang aus der Glocke der Achtsamkeit',
  'https://www.jalalldor.de/nussblog/jalalldor/der-gluecksklang-von-jalall-dor-glocke-der-achtsamkeit/',
  'Unser Glücksklang ist eine Klanginstallation oder Performance, die, angeregt durch die Skulptur Projekte Münster 2017, nun auch die friedliche Energie des Marktplatzes nach außen klingen lässt.\n \nUrsprünglich soll der Klang aus der Messing-Glocke aus dem Iran den Besucher des Markstandes daran erinnern, ins Hier und Jetzt zurückzukehren und sich zu erfreuen an der besonderen Atmosphäre auf dem Markt im Schatten des imposanten Paulus-Domes, in Sichtweite des gotischen Rathauses (Hier wurde 1648 der westfälische Frieden geschlossen).\n \nDorothea & Jalalledin schlagen mit ihrer Geschäftsidee eine Brücke zwischen Persien & Westfalen. Auch die Messingglocken tragen zum Brückenschlag bei. \n \nDie Marktstände von Jalall D‘or stehen an einem wunderbaren bedeutungsvollen Ort. Hier ist der Ursprung der Stadt, hier wurde der westfälische Frieden geschlossen und hier kommunizieren die persischen Glocken hin und wieder mit den gewaltigen westfälischen Glocken des Domes. Hier verträgt sich westfälisches Urgestein mit Händlern aus dem Orient. Hier hält man trotz aller Unterschiedlichkeit zusammen, weil man aufeinander angewiesen ist.\n \nMit dem Schlagen der Glocken möchte Jalall D‘or diese schöne friedliche Energie nach außen tragen. \n \nDer Glücksklang ist nun auch Friedensklang. Vielleicht inspiriert von der Kraft des Momentes nehmen einige Besucher die Erinnerung an das Glück und den Frieden mit nach Hause oder tragen sie sogar hinaus in die Welt.',
  'Mittwoch und Samstag, 7.00 h - 14.30 h',
  'auf dem Wochenmarkt in Münster in der Nussgalerie (Marktstand, der auch als kleine Galerie genutzt wird) von Jalall D\'or',
  'Klanginstallation / Performance',
  'Skulptur',
  '51.962605',
  '7.626172',
  'Nussgalerie.jpg',
  [ '2017-08-16',
    '2017-08-19',
    '2017-08-23',
    '2017-08-26',
    '2017-08-30',
    '2017-09-02',
    '2017-09-06',
    '2017-09-09',
    '2017-09-13',
    '2017-09-16',
    '2017-09-20',
    '2017-09-23',
    '2017-09-27',
    '2017-09-30' ],
  'repeating' ]
,
[ '23.07.2017 20:13:22',
  'Jaffke, Birgit',
  'Kindheitstraum',
  'www.farbig-und-rostig.de',
  'Lebensgroßes Pferd aus Schrott',
  'Montag bis Freitag, jeweils von 08:00 Uhr bis 17:00 Uhr',
  'Gut Havichhorst, Havichhorster Mühle 100, 48157 Münster ',
  'Ausstellung',
  'Skulptur',
  '52.005120',
  '7.685990',
  '',
  '',
  'always' ]
,
[ '23.07.2017 20:27:52',
  'Firgau, Renate',
  'Labyrinth',
  '',
  'Begehbares Bodenlabyrinth im Vorgarten - also auf kleinem Raum.\nLabyrinthe gibt es in vielen Kulturen der Welt. Alle sind irgendwie anders - und haben doch viele Gemeinsamkeiten. Die Wichtigste: man kann sich nicht verlaufen, es ist nämlich kein Irrgarten! Es gibt nur einen Weg, aber dieser ist voller Wendungen und Überraschungen - genau wie das Leben, für welches das Labyrinth symbolisch steht.',
  'Mittwoch, 26.7., 2.8., 9.8., jeweils 15 - 19 Uhr, andere Zeiten nach Vereinbarung.',
  'Sibeliusstr. 20, 48147 Münster, im Vorgarten',
  'im Vorgarten',
  'Begehbares Bodenlabyrinth',
  '51.982013',
  '7.648526',
  '',
  [ '2017-07-26', '2017-08-02', '2017-08-09' ],
  'repeating' ]
,
[ '27.07.2017 16:18:34',
  'Jalall D\'or (Jalalledin Eshaghi & Dorothea Linnenbrink)',
  'Ein Klang für Glück & Frieden',
  'www.jalalldor.de',
  'Unser Glücksklang ist eine Klanginstallation, eine Performance, die, angeregt durch die Skulptur Projekte Münster 2017, auch zum Friedensklang wird.\n\nUrsprünglich soll der Klang aus der Messing-Glocke aus dem Iran den Besucher des Markstandes daran erinnern, ins Hier und Jetzt zurückzukehren und sich zu erfreuen an der besonderen Atmosphäre auf dem Markt im Schatten des imposanten Paulus-Domes, in Sichtweite des gotischen Rathauses \n(Hier wurde 1648 der westfälische Frieden geschlossen).\n\nDorothea & Jalalledin schlagen mit ihrer Geschäftsidee eine Brücke zwischen Persien & Westfalen. Auch die Messingglocken tragen zum Brückenschlag bei. \n\nDie Marktstände von Jalall D‘or stehen an einem wunderbaren bedeutungsvollen Ort. Hier ist der Ursprung der Stadt, hier wurde der westfälische Frieden geschlossen und hier kommunizieren die persischen Glocken hin und wieder mit den gewaltigen westfälischen Glocken des Domes. Hier verträgt sich westfälisches Urgestein mit Händlern aus dem Orient. Hier hält man trotz aller Unterschiedlichkeit zusammen, weil man aufeinander angewiesen ist.\n\nMit dem Schlagen der Glocken möchte Jalall D‘or diese schöne friedliche Energie nach außen tragen. \n\nDer Glücksklang wird nun auch zum Friedensklang. Vielleicht inspiriert von der Kraft des Momentes nehmen einige Besucher die Erinnerung an das Glück und den Frieden mit nach Hause oder tragen \nsie sogar hinaus in die Welt. \n',
  'Mittwoch & Samstag 7.00 - 14.30 h',
  'Wochenmarkt am Dom',
  'Performance',
  'Klanginstallation',
  undefined,
  undefined,
  undefined,
  undefined,
  undefined ]
,
[ '30.07.2017 23:20:30',
  'Cassiopeia #1',
  'Cassiopeia #1 ',
  '',
  'a/v Konzert mit Sterile Garden, Lavas/Magmas, Les Horribles Travailleurs, this honourable fish',
  '21-23 Uhr ',
  'Schildkröte, Am Mittelhafen',
  'Event',
  'audiovisuelles Konzert',
  '51.9508',
  '7.644649',
  '',
  [ '2017-07-31' ],
  'once' ]
,
[ '17.08.2017 14:30:23',
  'Anja Kreysing',
  'Performance-Konzert mit livepainting-Videobeams & Ausstellung',
  'www.swfilmmuenster.de',
  'Kunstevent Ausstellungshalle Am Hawerkamp 31 & Schwarz-weiss ist die bessere Farbe: Sonderöffnung Ausstellungen, Speis & Trank. Ab 20.30 Uhr Performance-Konzert mit Live-Painting & Videobeams mit Live-Soundtrack -Poesie pur von und mit Stefano Giorgi (vis.) & Vittorio Garis (perc.), Ulrike Lentz (fl.), Anja Kreysing (akk.), Helmut Buntjer (tb) Eintritt 5 €',
  '19-23 Uhr',
  'Ausstellungshalle am Hawerkamp 31',
  'Performance',
  'Film / Video / Licht',
  '51.943878',
  '7.638363',
  '',
  [ '2017-09-01' ],
  'once' ]
,
[ '05.09.2017 18:00:46',
  'Miss Miri',
  'Mandala Wonderland',
  'www.impulseearth.com',
  'Das "Mandala Wonderland" wird am 16. September im Know Me Nähatelier und im Hinterhof der Diepenbrockstr. 11 stattfinden. Am Samstag kann man sich dort die von der Künstlerin Miss Miri kriierten Mandala Unikate auf Leinwand (Fotografie transformiert zu Mandalas) anschauen. Am Sonntag findet zusätzlich ein interaktiver offener Workshop statt, an dem man sich im Mandalaweben mit Wolle und Holz ausprobieren kann. Materialien gibt es vor Ort, über Wollespenden freuen wir uns immer. ',
  '',
  'Know Me Atelier Diepenbrockstr. 11',
  'Ausstellung und Workshop ',
  'Digitale Mandalas - Fotokunst ',
  '51.9586421',
  '7.64011679',
  '',
  [ '2017-09-16' ],
  'once' ]
,
[ '03.07.2017 17:49:52',
  'Kubeja, Jochen',
  'Guerilla-Skulptur: "Ride on the shoulders of ÖZIL" oder so',
  'www.wohnzimmer-ev.de',
  'Skulptur zum Quadrat: Die dem Fußballgott ÖZIL nachempfundene, silbrige Skulptur, die einem Denkmal gleicht, war längere Zeit verschollen, steht aber nun wieder auf seinem Platz vor der Halle Münsterland. Die aus dem Nichts auftauchende SchattenSkulptura, eine silberfarbige Figur in einem Morphsuit, wurde auf den Schultern des Fußballers platziert. Beide korrespondieren in Form und Farbe, harmonisieren federleicht und zu einer Einheit verschmolzen. ',
  'Rund um die Uhr',
  'Albersloher Weg 32, 48155 Münster',
  'Ausstellung',
  'Skulptur',
  '51.94872',
  '7.63871',
  '',
  '',
  'always' ]
,
[ '12.06.2017 19:24:13',
  'Kubeja, Jochen',
  'Graffiti-Werke - Urban Street Art',
  'www.wohnzimmer-ev.de',
  'Im Rahmen des diesjährigen Viertelfestes am Sa. 24.06.2017 entstand in Wurfweite des Staufenplatzes dieses Street-Art-Graffiti-Werk des lokal geschätzten Künstlers Rookie the Weird. Auf dem Bild ist deutlich seine Handschrift zu lesen: Krokodil, Affen, Wunderland. Have a look of new Weirdation.',
  'Rund um die Uhr',
  'Staufenstraße 9, Münster',
  'Ausstellung',
  'Urban Street Art',
  '51.96453',
  '7.64226',
  '',
  '',
  'always' ]
,
[]];
