var SchattenSkulpturEvents = [
[ '21.03.2017 22:33:46',
  'Kubeja, Jochen',
  'WoGA Garten',
  '',
  'Skulpturen-Garten',
  'So., 14 - 18 Uhr',
  'Zum Guten Hirten 109',
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined ]
,
[ '03.04.2017 20:18:48',
  'Kubeja, Jochen',
  'Graffiti Kunst',
  '',
  'Die Fabrikwand ist offiziell erlaubte Graffiti-Fläche. Kunst-Studierende sprühen hier gerne ihre Werke an die Wand. So entsteht eine ständig wechselnde Graffiti-Ausstellung auf hohem Niveau. Häufig sind die Künstler/innen bei der Arbeit anzutreffen.',
  'immer',
  'Euler Str. 21, Münster',
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined ]
,
[ '03.04.2017 20:43:06',
  'Kubeja, Jochen',
  'Elefant',
  'www.wohnzimmer-ev.de',
  'Ein aus weißem Marmor gehauener Elefant, etwa 1,10 groß',
  'immer',
  'Nieberdingstr. 11, 48155 Münster',
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined ]
,
[ '10.04.2017 12:29:32',
  'Jaffke, Michael',
  'Die Große',
  'www.farbig-und-rostig.de',
  'Skulpur aus Schrott und Holz',
  'August 2017',
  'noch unbekannt',
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined ]
,
[ '02.05.2017 19:39:16',
  'Kubeja, Jochen',
  'Critical Mass Münster',
  'https://www.facebook.com/criticalmass.ms/',
  'Werde Teil der Masse und zeig, dass Radfahrer im Verband im Straßenverkehr ein  s werden und zu einem riesigen Fahrzeug verschmelzen. \n\n> 16 Radfahrer = Verband = auf der Straße fahren \n\nKeine Demo, Veranstaltung oder Rennen, sondern Performance, Flashmob und Haltung. Und auch einfach und entspannt mit anderen durch die Stadt radeln.\n\nSpät dran oder Start verpasst? Kein Problem!\nMit den Apps Critical Maps und Glympse könnt ihr uns auch als Nachzügler noch finden und zur Masse dazustoßen.\nCritical Maps: Einfach App runterladen und öffnen. Der aktuelle Standort der CM wird angezeigt.\nGlympse: App runterladen und nach dem Tag "criticalmassMS" suchen, auch hier wird dann der Standort angezeigt.\nFür alle die pünktlich da sind: Ladet euch doch auch die App runter, startet Sie beim losfahren und teilt damit euren Standort. Das ermöglicht den anderen uns zu finden. Je mehr Leute mitmachen, desto genauer wirds!\n\nBis gleich!\n',
  'Fr., 26.05.2017\nFr., 30.06.2017\nFr. 28.07.2017\nFr. 25.08.2017\nFr., 29.09.2017\nStart ist jeweils um 19.00 Uhr.',
  'Treffpunkt Domplatz Münster',
  'Kunst-Flashmob',
  '',
  '51.962077',
  '7.625366',
  '102',
  [ '2017-05-26',
    '2017-06-30',
    '2017-07-28',
    '2017-08-25',
    '2017-09-29' ] ]
,
[ '03.05.2017 12:06:30',
  'Weyand, Georgios',
  'Der Sonnenwagen',
  'http://www.facebook.com/DerSonnenwagen/',
  'Kinetische Gemeinschafts-Skulptur mit medialer Installation',
  '24h ohne mediale Installation an der Dammstr. 19 - an ausgewählten Tagen und Orten mit medialer Installation',
  'Dammstr. 19 / verschiedene Orte in Münster',
  'Sonstiges',
  '',
  '51.951001',
  '7.632366',
  '103',
  undefined ]
,
[ '04.05.2017 19:49:13',
  'Künnemann, Ursula',
  'Skulpturen-Garten Ahlener Gruppe',
  '',
  'Gegenüber des Zwingers an der Promenade führt ein schmaler Weg (markiert) direkt in den einladenden Skulpturen-Garten. Die Ahlener KünstlerInnengruppe arbeitet seit über 10 Jahren an Skulpturen aus Sandstein und Speckstein. Eine Auswahl der Werke präsentieren sie in dem hausumläufigen Garten. Die Gruppe verbindet der Werkstoff, die Motivwahl erfolgt individuell durch die jeweilige KünstlerIn. Die Künstler sind anwesend und arbeiten zum Teil vor Ort.',
  'Sa., 29.08.2017, 12.00 bis 18.00 Uhr',
  'Zeppelinstr. 6, 48147 Münster',
  'Ausstellung',
  '',
  '51.968199',
  '7.631402',
  '',
  [ '2017-08-29' ] ]
,
[ '02.06.2017 14:15:52',
  'Schulze, Einar',
  'Vernissage "lyme" von Einar Schulze bei KnowMe',
  'irgendeinar.blogspot.de',
  'Ölgemälde von Einar Schulze, ausgestellt bei KnowMe.',
  '24. Juni - 24. Juli 2017 / Mittwochs 9 – 16 Uhr und Freitags 9 – 14 Uhr',
  'Diepenbrockstraße 11, Hinterhof, 48145 Münster',
  'Ausstellung',
  'Gemälde',
  '51.958503',
  '7.640315',
  '',
  [ '2017-06-24' ] ]
,
[ '09.05.2017 19:34:15',
  'Kordt, Monika Veronika',
  'Kunstgewirk',
  '',
  'Unterschiedliche gestaltete Stühle',
  'Steht noch nicht fest',
  'Steht noch nicht fest',
  'Event',
  undefined,
  undefined,
  undefined,
  undefined,
  undefined ]
,
[ '12.05.2017 15:55:24',
  'Luckmann, Helmut',
  'Aus-Stellung, Aus-Schnitte',
  '',
  'Im Rahmen eines "Offenen Aleliers" ist u.a. das Bild zu sehen, das im letzten Jahr bei einer Performance im Schlossgarten entstand. \nDie Tänzer Alice Cerrato und Antonio Rusciano begleiten eine Transformation dieses großen Bildes, bei der die Besucher einen bestimmten Aussnitt wählen können, der von mir vor Ort zu einem neuen Objekt gestaltet wird.\nWir geben auch gerne Autogramme ins Booklet, das die gesamte Performance inkl. DVD dokumentiert.\nDie einzelnen Aktionen werden jeweils um 12, 14, und 16 Uhr starten. \nSie sind herzlich eingeladen, sich an diesem Tag inspirieren und überraschen zu lassen. ',
  'So., 11.06.2017, 11 bis 17 Uhr',
  'Atelier Werse 27, Pleistermühlenweg, Biohof Borghoff',
  'Ausstellung',
  'Gemälde',
  undefined,
  undefined,
  undefined,
  undefined ]
,
[ '15.05.2017 14:11:37',
  'Teresa Häuser',
  'womens march Münster',
  'Werkstatt-Kinderhaus.de',
  '\n    "Women’s march – Münster" eine Skulpturenarbeit der "Werkstatt für Gestaltung"\n\nWir formen eine Skulpturengruppe aus Figuren, die in der "Werkstatt für Gestaltung" von vielen kunstschaffenden Menschen entstanden sind. Dazu gießen wir unsere vorhandenen Tonskulpturen, die wir 2016 zusammen bei der Ausstellung "Kunst am Rand" als "Frauen in Münster" gezeigt haben, mit Gips ab und replizieren daraus viele neue Büsten aus Pappmaschee. Diese entstandenen Doubles unserer Sklupturen grundieren wir mit pinker Farbe, kleistern nochmal eine Schicht Zeitungspapier darauf und stellen sie gesammelt in verschiedenen Formationen zum "women´s march" auf. Die Figuren beenden ihren Marsch schlussendlich an der Wiese gegenüber dem Aasee/Promenade. Wir holen damit die mittlerweile internationale Bewegung "womens march" (urspünglich aus den USA) nach Münster und eroberen uns den öffentlichen Raum der Stadt zurück, der im Rahmen den "Skulptur-Projekte 2017" nur von international renommierten, aber nicht aus Münster stammenden Künstlern belegt ist. Der Platz an der Promenade ist bewusst als "Dialog" zu dem Motto „Münster bekennt Farbe“ gewählt – und versucht eine Erweiterung und Übertragung des hübschen, blumigen Spruchs: In Anlehnung an die pinken „women’s hats“ der Bewegung sind unsere Figuren pink und repräsentieren die verschiedenen, vielfältigen Menschen unserer Stadt, sichtbar durch unterschiedliche Altersstufen, Kulturgruppen, Ethnien, Religionszugehörigkeiten, Geschlechter. Die Zeitungen, die in der äußeren Ummantelung der Figuren verwendet werden, sind international und stellen eine Anspielung auf die Sprachenvielfalt und Pressefreiheit, mithin eine Reminiszenz an die Allgemeinen Menschenrechte dar.\n',
  'im Zeitraum 11.-17.9.2017',
  'Am Liebsten auf der Wiese Promenade/Aasee "Münster bekennt Farbe" als Abschluss. Eventuell auch andere Plätze an der Promenade die , die Bewegung dorthin markieren. Uns ist noch nicht klar, ob wir die Veranstaltung als Mahnwache/Demonstration oder Kunstausstellung anmelden. Wir arbeiten an dieser Frage und würden das Projekt bis zur  Beantwortung derselben noch nicht veröffentlichen wollen. ',
  'Ausstellung',
  'Skulptur',
  '51.957270',
  '7.620800',
  '',
  [ '2017-09-11' ] ]
,
[ '18.05.2017 18:42:49',
  'Cardaun, Gilla',
  'Fahrt ins Blaue',
  'www.ambulantegalerie.de',
  'Ein umgestaltetes Verkehrs-Schild, bemalt mit Acrylfarbe',
  'Mo - Fr: 10 bis 18 Uhr\nSa: 10 - 14 Uhr',
  'In der Fahrrad-Werkstatt Lila Leeze, Dortmunder Str. 11, 48155 Münster',
  'Ausstellung',
  'Gemälde',
  '51.955298',
  '7.641913',
  undefined,
  undefined ]
,
[ '18.05.2017 20:09:09',
  'SchattenSkulptura',
  'Offizieller Auftakt SchattenSkulptura',
  'www.wohnzimmer-ev.de',
  'Zum Auftakt unserer SchattenSkulptura starten wir mit einem Kunst-Picknick an der Promenade. Bringt Picknick-Decken mit und alles, was dazu gehört. Also lecker Essen und Trinken, Kerzenfackeln, Instrumente, Mucke... \nUnd: Natürlich ein Stück Kunst. Oder auch zwei.\nKommt vorbei und startet mit uns in den ultimativen Kunst-Sommer! \n(JedeR nimmt mit nach Haus, was er/sie mitbringt)',
  'Freitag, 16.06.2017 ab 20 Uhr',
  'Promenade, auf der Wiese direkt westlich vom Zwinger ',
  'Flashmob',
  'Skulptur',
  '51.967742',
  '7.630874',
  '',
  [ '2017-06-16' ] ]
,
[ '23.05.2017 19:40:51',
  'Kayalie, Fouad',
  'Syrian Sculptures - Gips and Beton',
  '',
  'Es werden Fotos hinterlegt, die die Kunst beschreiben...',
  'Nach Terminvereinbarung - suche Außerdem Ausstellungsräume oder Gemeinschaftsausstellungen',
  'Die Skulpturen stehen bei mir im Wohnzimmer. Kontaktiere mich und wir können einen Termin vereinbaren: fouadkayalie@gmail.com',
  'Ausstellung',
  'Skulptur',
  '51.983640',
  '7.641120',
  '101',
  undefined ]
,
[ '25.05.2017 20:14:53',
  'Kötter, Lisa',
  'Skulptur-to-go- Automat',
  'strohzugoldlisa.blogspot.de',
  'Ich werde einen fahrbaren Skulpturen-"Automaten" bauen. Dort kann jeder gegen eine kleine spende eine kleine Skulptur für die Hosentasche( und dann zu Hause fürs Sideboard) erstehen. \nDie Kunstfreunde werden mit dem "Automaten" auch reden können, er kann Fragen  zu den kleinen Kunstwerken beantworten.\nDie kleinen Skulpturen werden von mir persönlich ( vor allem aus upgecycleten  Altmaterial) gefertigt und in entsprechend gestaltete Streichholzschachteln verpackt, die jeweils Teil des kleinen Werkes sein werden.\n\nIch bin freischaffende Künstlerin aus Münster. Nah Göttingen habe ich ein zweites Atelier. Seit über 20 Jahren mache ich meine Kunst vor allem aus Altmaterialien. So ist der Name meines Blogs "strohzugold" Programm.\nVielen Dank für diese tolle Idee der Schattenskulptur! Und für die Möglichkeit zur Vernetzung. ',
  '(16.,)17.,18. Juni, 24.,25. Juni, 1.,2. Juli, 22,.23. Juli jeweils ca.14-16 Uhr',
  'Um die Kreuzschanze herum (Promenade)',
  'Fahrbarer "Automat"',
  'Skulpturen- "Automat"',
  undefined,
  undefined,
  undefined,
  undefined ]
,
[ '06.06.2017 23:06:05',
  'Eckardt, Linda',
  'Phantastische Malerei',
  '',
  'Acryl auf Leinwand',
  '',
  'Drinnen in einem Zimmer, Raum, Halle',
  'Ausstellung',
  'Gemälde',
  '51.934346',
  '7.594275',
  undefined,
  undefined ]
,
[ '12.06.2017 14:58:15',
  'Jaffke, Michael',
  'Offenes Atelier "farbig und rostig"',
  'www.farbig-und-rostig.de',
  'Wir öffnen unser Atelier und zeigen unsere neuesten Objekte, aber auch ältere Werke der letzten Jahre. Es handelt sich dabei um Acrylbilder, sowie Skulpturen aus Schrott und Fundstücken. \nDie Location liegt am Ufer der Werse und ist am Besten mit dem Fahrrad oder zu Fuß erreichbar. Autofahrer könnten evtl. Parkprobleme bekommen und sollten in der Umgebung der Kapelle am Beginn der Zielstraße parken.\nNähere Infos unter www.farbig-und-rostig.de',
  '09.09., 10.09., 23.09., 24.09. jeweils von 11 bis 18 Uhr',
  '48157 Münster, Reetbusch 71',
  'Ausstellung',
  'Skulpturen und Acrylbilder',
  '51.971413',
  '7.696116',
  '',
  [ '2017-09-09', '2017-09-10', '2017-09-23', '2017-09-24' ] ]
,
[ '12.06.2017 17:37:14',
  'Kubeja. Jochen',
  'Graffiti-Wand - Urban Street Art',
  'www.wohnzimmer-ev.de',
  'Zwischen Nieberdingstraße und Kanalufer führt ein Weg zur Marine Jugend e. V. entlang der Gebäuderückseite von Getränke Lappe. Diese Wand wird von zahlreichen, tollen Graffiti-Werken verziert. Wahre Urban Street Art von bekannten und geschätzten Künstlern wie Rookie the Weird (www.facebook.com/liquidluck.de) und vielen Anderen',
  'Rund um die Uhr',
  'Nieberdingstraße 12, 48155 Münster (Gebäuderückseite)',
  'Urban Street Art',
  'Graffiti',
  '51.944291',
  '7.644210',
  undefined,
  undefined ]
,
[ '12.06.2017 18:07:23',
  'Kubeja, Jochen',
  'Graffiti-Wand Rebholz - Urban Street Art',
  'www.wohnzimmer-ev.de',
  'Die Gebäudewand der Eisen- und Metallgießerei Rebholz ist eine der lebhaftesten und beliebtesten Graffiti-Wände der Stadt. Die Ausstellung ist ständig im Wandel. Qualitativ hochwertige Werke sind hier zu bestaunen. Seit 2007 ist die Wand durch die Ordnungspartnerschaft Graffiti für Sprayer freigegeben. Ein Besuch lohnt sich immer. Insbesondere am Wochenende sind die Künstler bei der Arbeit anzutreffen. ',
  'Rund um die Uhr',
  'Euler Straße 21, 48155 Münster',
  'Ausstellung',
  'Graffiti - Urban Street Art',
  '51.941264',
  '7.639899',
  undefined,
  undefined ]
,
[ '12.06.2017 19:27:23',
  'Kubeja, Jochen',
  'Schiff',
  'https://www.facebook.com/Das-Nieber-Ding-eV-1406239566266186/',
  'Der Künstler Daniel Dubbrow ist versiert im Umgang mit Holz. Aus Holzresten und Holzabfällen kreiert er fantastische Skulpturen, die in der Regel begehbar und erlebbar sind. So auch sein Schiff von 2016, das am NieberDing vor Anker liegt. Über einen Holzsteg, gesäumt von dicken Tauen, kann das Schiff betreten werden. Aber Vorsicht, der Seegang ist nicht ganz ohne und schüttelt das Schiff samt Passagiere mächtig durch. ',
  'Rund um die Uhr',
  'Nieberdingstr. 26, 48155 Münster. Wiese nördlich vor dem Haus',
  'Ausstellung',
  'Skulptur',
  '51.942200',
  '7.643010',
  undefined,
  undefined ]
,
[ '12.06.2017 18:42:53',
  'Kubeja, Jochen',
  'Schiffer-Schaukel',
  'https://www.facebook.com/Das-Nieber-Ding-eV-1406239566266186/',
  'Ein weiteres Upcycling-Werk des Künstlers Daniel Dubbrow und Freunden, die Schiffer-Schaukel, das ebenfalls "begehbar" und erlebbar ist. Steig ein, schließ die Augen und lass die Seele baumeln...',
  'Rund um die Uhr',
  'Nieberdingstraße 26, 48155 Münster. Wiese nördlich vor\'m Haus',
  'Ausstellung',
  'Skulptur',
  undefined,
  undefined,
  undefined,
  undefined ]
,
[ '12.06.2017 19:11:22',
  'Kubeja, Jochen',
  'Graffiti-Gemälde Under the Bridge',
  'www.wohnzimmer-ev.de',
  'Unter der Umgehungsstraßen-Brücke ist das wohl größte Graffiti-Gemälde der Stadt zu sehen. Die komplette östliche Wand ziert ein Werk, thematisch passend zur Wasserkante. ',
  'Rund um die Uhr',
  'Unter der Umgehungsstraßenbrücke, Eulerstraße 15',
  'Ausstellung',
  'Gemälde',
  '51.939389',
  '7.638609',
  undefined,
  undefined ]
,
[ '12.06.2017 19:24:13',
  'Kubeja, Jochen',
  'Graffiti-Werke - Urban Street Art',
  'www.wohnzimmer-ev.de',
  'Am Hawerkamp finden sich überall außergewöhnliche Graffitis, geschweisste Skulpturen und vielfältige Urban Street Art.\n"Ein besonderes Gebiet in Münster zum Ausgehen ist der Hawerkamp [... Hier] hat sich eine außergewöhnliche künstlerische und musikalische Szene etabliert, die jährlich über 120.000 Besucher anzieht. Neben den zahlreichen Musikevents in den einzelnen Clubs ist diese Besucherzahl auch auf das jährlich stattfindende Hawerkamp-Festival und den offenen Ateliers der über 50 Künstler zurückzuführen. Bei der Bewerbung Münsters zur Kulturhauptstadt Europas 2010 war der Hawerkamp einer der kulturellen Schwerpunkte neben Prinzipalmarkt und Picasso-Museum. In einem bundesweit einzigartigen Projekt wird seit dem 1. Januar 2006 das alternativ geprägte Gelände durch den Verein "Erhaltet den Hawerkamp" eigenverantwortlich verwaltet."\nQuelle: http://wiki.muenster.org/index.php/Hawerkamp',
  'Rund um die Uhr',
  'Am Hawerkamp 31, Münster',
  'Ausstellung',
  'Urban Street Art',
  '51.943878',
  '7.638363',
  undefined,
  undefined ]
,
[]];
